<?php
/**
 * Desyncr\ConnectedTest\Service
 *
 * PHP version 5.4
 *
 * @category General
 * @package  Desyncr\ConnectedTest\Service
 * @author   Dario Cavuotti <dc@syncr.com.ar>
 * @license  https://www.gnu.org/licenses/gpl.html GPL-3.0+
 * @version  GIT:<>
 * @link     https://github.com/desyncr
 */
namespace Desyncr\ConnectedTest\Service;

use Desyncr\Connected\Service\AbstractService;

class ConcreteService extends AbstractService
{
    public function dispatch()
    {
        return count($this->frames);
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
class AbstractServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConcreteService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::setOptions
     */
    public function testSetOptions()
    {

        $options = array(
            'timeout' => 10,
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['timeout'], $this->object->timeout);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::setOptions
     */
    public function testSetOptionsNestedArray()
    {

        $options = array(
            'names' => array(
                'John Doe',
                'Jane Doe',
                'Alice',
                'Bob'
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['names'], $this->object->names);
        $this->assertEquals($options['names'][0], $this->object->names[0]);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::setOptions
     */
    public function testSetOptionsNestedArrayLevel()
    {

        $options = array(
            'servers' => array(
                'frontend' => array(
                    array('host' => '127.0.0.1', 'port' => 80),
                    array('host' => '127.0.0.1', 'port' => 81)
                ),
                'backend' => array(
                    array('host' => '127.0.0.1', 'port' => 8888)
                )
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['servers']['frontend'], $this->object->servers['frontend']);
        $this->assertEquals($options['servers']['frontend'][1]['port'], $this->object->servers['frontend'][1]['port']);
        $this->assertEquals($options['servers'], $this->object->servers);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::getOption
     */
    public function testGetOption()
    {
        $options = array(
            'servers' => array(
                'frontend' => array(
                    array('host' => '127.0.0.1', 'port' => 80)
                )
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($this->object->getOption('servers'), $options['servers']);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::add
     */
    public function testAdd()
    {
        $key = 'frame.service.key';
        $frame = array();
        $frameObject = $this->object->add($key, $frame);

        $this->assertEquals('Desyncr\Connected\Frame\BaseFrame', get_class($frameObject));
        $this->assertEquals($frameObject->getId(), $key);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::add
     */
    public function testAddInvalidJob()
    {
        $key = 'frame.service.key';
        $frame = new \StdClass;
        $this->setExpectedException('Exception');

        $this->markTestIncomplete('API change will support custom objects');
        $this->object->add($key, $frame);
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::dispatch
     */

    public function testDispatch()
    {
        $key = 'frame.service.key';
        $frame = array();
        $this->object->add($key, $frame);

        $this->assertEquals(1, $this->object->dispatch());
    }
}
