<?php
namespace Desyncr\Connected\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
class AbstractServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('AbstractService');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Desyncr\Connected\Service\AbstractService::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
